#!/usr/bin/env python

"""
depreciated. will delete once confirmed replacement is funcitonal

"""

import rospy
import sys
from intera_core_msgs.srv._IOComponentCommandSrv import IOComponentCommandSrv
from intera_core_msgs.msg._IOComponentCommand import IOComponentCommand


def camera_command_client(camera, status, timeout=0.0):
    rospy.wait_for_service('/io/internal_camera/' + camera + '/command')
    try:
        cam_control = rospy.ServiceProxy('/io/internal_camera/' + camera + '/command', IOComponentCommandSrv)
        cmd = IOComponentCommand()
        cmd.time = rospy.Time.now()
        cmd.op = 'set'
        if status:
            cmd.args = '{"signals": {"camera_streaming": {"data": [true], "format": {"type": "bool"}}}}'
        else:
            cmd.args = '{"signals": {"camera_streaming": {"data": [false], "format": {"type": "bool"}}}}'

        resp = cam_control(cmd, timeout)
        print resp
    except rospy.ServiceException as e:
        print("Service call failed: %s"%e)


if __name__ == '__main__':
    rospy.init_node('camera_command_client')

    if len(sys.argv) < 2:
        print("usage: camera_switcher active_camera (head, arm)")
    else:
        if sys.argv[1] == 'head':
            camera_command_client(camera='right_hand_camera', status=False)
            camera_command_client(camera='head_camera', status=True)
        elif sys.argv[1] == 'arm':
            camera_command_client(camera='head_camera', status=False)
            camera_command_client(camera='right_hand_camera', status=True)

