#!/usr/bin/env python

"""
This file acts as a wrapper for the intera interface to control the sawyer arm.
It contains a class with various methods for a controlling the sawyer arm to
throw a bean bag.
"""

from __future__ import division
import numpy as np
import rospy

from the_mighty_sawyer import MoveArm

import intera_interface
from intera_interface import CHECK_VERSION

import geometry_msgs.msg
from std_msgs.msg import String


def main():

    rospy.init_node('throw_with_sawyer', anonymous=True)

    testing = MoveArm()

    testing.InitializeGripper()

    testing.go_to_recieving_pos()

    testing.OpenGripper()

    testing.go_to_bag_pos()

    testing.CloseGripper()

    rospy.sleep(1)

    # testing.do_under_hand_toss()

    testing.overhand_throw_start()

    rospy.sleep(2)

    testing.overhand_throw()

    testing.go_to_recieving_pos()

    rospy.sleep(3)

    print("Done")

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
