#!/usr/bin/env python
"""


Publishers:
	Pose - Pose estimation from AprilTags
"""

import rospy
from geometry_msgs.msg import Pose



def main():
	rospy.initnode("locate_board_pub" anonymous=True)
	
	#== publish Pose
	rospy.Publisher("", Pose, queue_size=10)


if __name__ == "__main__":
	try:
        main()
    except rospy.ROSInterruptException:
        pass