#!/usr/bin/env python
# import roslib
# roslib.load_manifest('my_pkg_name')
import rospy
import actionlib

from the_mighty_sawyer.msg import (
  ThrowAction,
  ThrowActionFeedback, 
  ThrowActionGoal,  
  ThrowActionResult, 
  ThrowFeedback, 
  ThrowGoal, 
  ThrowResult
)

if __name__ == '__main__':
  rospy.init_node('throw_action_client')
  _action_name = 'throw_base'
  client = actionlib.SimpleActionClient('throw_base', ThrowAction)
  client.wait_for_server()
  goal = ThrowActionGoal()
  
  # Fill in the goal here
  client.send_goal(goal)
  client.wait_for_result(rospy.Duration.from_sec(5.0))